<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;

class BusinessTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $items = [
            [
                'id' => '980ae2bb-1ba6-46fd-bed0-95c4fdf5d01f',
                'refID' => 'BUS-TYPE'.'-'.str_pad((0), 4, "0", STR_PAD_LEFT),
                'corporation' => '0',
                'name' => 'Sole Proprietorship',
                'description' => 'A sole proprietorship is easy to form and gives you complete control of your business.',
                'created_at' => Carbon::now(),
            ],
            [
                'id' => '980ae2d5-8a0c-4e57-ad77-b9f1d0a8d4c9',
                'refID' => 'BUS-TYPE'.'-'.str_pad((1), 4, "0", STR_PAD_LEFT),
                'corporation' => '0',
                'name' => 'Partnership',
                'description' => 'Partnerships are the simplest structure for two or more people to own a business together. There are two common kinds of partnerships: limited partnerships (LP) and limited liability partnerships (LLP).',
                'created_at' => Carbon::now(),
            ],
            [
                'id' => '980ae32a-3d12-46f0-9156-5eb8db133e6c',
                'refID' => 'BUS-TYPE'.'-'.str_pad((2), 4, "0", STR_PAD_LEFT),
                'corporation' => '0',
                'name' => 'Limited liability company (LLC)',
                'description' => 'An LLC lets you take advantage of the benefits of both the corporation and partnership business structures.',
                'created_at' => Carbon::now(),
            ],
            [
                'id' => '980ae350-6e48-4700-ac4d-8c4f3be9a9b0',
                'refID' => 'BUS-TYPE'.'-'.str_pad((3), 4, "0", STR_PAD_LEFT),
                'corporation' => '0',
                'name' => 'Corporation',
                'description' => 'A corporation, sometimes called a C corp, is a legal entity that separate from its owners. Corporations can make a profit, be taxed, and can be held legally liable.',
                'created_at' => Carbon::now(),
            ],
            [
                'id' => '980ae37d-5ad7-455f-8e69-d949ba8319b8',
                'refID' => 'BUS-TYPE'.'-'.str_pad((4), 4, "0", STR_PAD_LEFT),
                'corporation' => '0',
                'name' => 'Cooperative',
                'description' => 'A cooperative is a business or organization owned by and operated for the benefit of those using its services. Profits and earnings generated by the cooperative are distributed among the members, also known as user-owners.',
                'created_at' => Carbon::now(),
            ],
        ];

        DB::table('business_types')->insert($items);

    }


}
